openapi: 3.1.0
info:
  title: bre
  version: '1.0'
  description: Used by Najm MOH Injury System to calculate Financial Liability Report result. The API accepts accident parties input data with their insurance policies coverage to calculate liability percentages for each party
  summary: Financial Liability Report
servers:
  - url: 'http://localhost:3000'
paths:
  /v1.0/workflows/Execute:
    parameters: []
    post:
      summary: ExecuteRule
      operationId: post-v1.0-workflows-WORKFLOW_NAME-?operation=execute
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/LaibilityResponse.yaml
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: number
                  errorMessage:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - errorMessage
                x-examples:
                  example-1:
                    errorCode: 2222
                    errorMessage: Input validation
      description: Used by Najm MOH Injury System to calculate Financial Liability Report result. The API accepts accident parties input data with their insurance policies coverage to calculate liability percentages for each party
      parameters:
        - $ref: '#/components/parameters/jsoncontent'
        - $ref: '#/components/parameters/bearertoken'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/LiabilityRequest.yaml'
            examples:
              example-1:
                value:
                  - workFlowName: string
                    identityNumber: string
                    isInjured: true
                    hasGOSI: true
                    hasMTPL: true
                    hasPA: true
                    hasMedical: true
                    liabilityPercentage: 0
      tags:
        - breapi
components:
  schemas:
    LaibilityResponse.yaml:
      type: array
      items:
        $ref: ../models/LaibilityResponse.yaml
    LiabilityRequest.yaml:
      title: LiabilityRequest.yaml
      type: object
      properties:
        workFlowName:
          type: string
        identityNumber:
          type: string
        isInjured:
          type: boolean
        hasGOSI:
          type: boolean
        hasMTPL:
          type: boolean
        hasPA:
          type: boolean
        hasMedical:
          type: boolean
        liabilityPercentage:
          type: number
  parameters:
    jsoncontent:
      name: content-type
      in: header
      required: false
      schema:
        type: string
      description: application/json
    bearertoken:
      name: Authorization
      in: header
      required: false
      schema:
        type: string
      description: Bearer XXXXXXXXXXXXXXXXXXXXXXXXSSSSSSSSSSSSSSSSSSSS
